from datetime import datetime


def create_email_html(stats):
    arrow = "📈" if stats["change"] > 0 else "📉" if stats["change"] < 0 else "➡️"

    html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {{
    font-family: Arial, sans-serif;
    background: #f5f5f5;
    padding: 30px;
}}

.card {{
    max-width: 600px;
    margin: auto;
    background: white;
    border-radius: 12px;
    padding: 25px;
    box-shadow: 0 2px 10px rgba(0,0,0,.1);
}}

h1 {{
    color: #C89B3C;
}}

table {{
    width: 100%;
    border-collapse: collapse;
}}

td {{
    padding: 10px;
    border-bottom: 1px solid #eee;
    font-size: 16px;
}}

.value {{
    text-align: right;
    font-weight: bold;
}}

.footer {{
    margin-top:20px;
    color:#777;
    font-size:13px;
}}
</style>
</head>

<body>

<div class="card">

<h1>🪙 Daily Gold Report</h1>

<p><b>{stats["date"]}</b></p>

<table>

<tr>
<td>Gold Rate</td>
<td class="value">₹{stats["current"]:,.0f}/g</td>
</tr>

<tr>
<td>Change</td>
<td class="value">{arrow} ₹{abs(stats["change"]):,.0f}</td>
</tr>

<tr>
<td>₹10,000 buys</td>
<td class="value">{stats["grams"]} g</td>
</tr>

<tr>
<td>Days Left This Month</td>
<td class="value">{stats["days_left"]}</td>
</tr>

</table>

<br>

<img src="cid:gold_graph" width="100%">

<div class="footer">
Generated by au-some bot by Anwesha
</div>

</div>

</body>
</html>
"""

    return html